# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:14.16.1
    steps:
      - checkout
      - run:
          name: Install all dependencies
          command: |
            npm install --save
      - run:
          name: Run BDD Tests
          command: |
            npm run student-record-bdd
      - store_test_results:  
          path: cucumber_report.html
      - store_artifacts:
          path: test-results
workflows:
  build_test:
    jobs:
      - run_tests
